version: '3.8'

services:
  app1:
    build: .
    environment:
      - PORT=3001
    ports:
      - "3001:3001"
    networks:
      - app-network

  app2:
    build: .
    environment:
      - PORT=3002
    ports:
      - "3002:3002"
    networks:
      - app-network

  app3:
    build: .
    environment:
      - PORT=3003
    ports:
      - "3003:3003"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
      - app3
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
